mongo:
  image: mongo:2.4

  ports:
    - 27017:27017

  volumes:
    - ./volumes/mongo:/data/db

node:
  build: ./node

  ports:
    - 3000:3000

  environment:
    - NODE_ENV=docker-development

  volumes:
    - ./node:/src

  links:
    - mongo