mongo:
  image: mongo:2.4

  ports:
    - 47017:27017

  volumes:
    - ./volumes/mongo:/data/db

node:
  build: ./node

  ports:
    - 3000:3000

  volumes:
    - ./node:/src

  links:
    - mongo

  command: ["node_modules/forever/bin/forever", "-w", "./server.js"]

nginx:

  build: ./nginx

  restart: always

  links:
    - node

  ports:
    - 80:80
    - 443:443