version: "3.3"

services:
  mongo:
    image: mongo:2.4
    restart: always

    volumes:
      - ./volumes/mongo:/data/db

  node:
    build: ./node
    environment:
      NODE_ENV: 'development'
    restart: always

    links:
      - mongo

  nginx:

    build: ./nginx
    restart: always

    links:
      - node

    ports:
      - 80:80
      - 443:443