mongo:
  image: mongo:2.4
  restart: always

  volumes:
    - ./volumes/mongo:/data/db

node:
  build: ./node
  restart: always

  links:
    - mongo

nginx:

  build: ./nginx
  restart: always

  links:
    - node

  ports:
    - 80:80