
var workMap = { 
  abstract:  'abstract',
  addressees_as_marked:  'addressees_as_marked',
  addressees_inferred:  'addressees_inferred',
  addressees_uncertain:  'addressees_uncertain',
  authors_as_marked:  'authors_as_marked',
  authors_inferred:  'authors_inferred',
  authors_uncertain:  'authors_uncertain',
  date_of_work_as_marked:  'date_of_work_as_marked',
  destination_id:  'destination_id',
  destination_as_marked:  'destination_as_marked',
  destination_inferred:  'destination_inferred',
  destination_uncertain:  'destination_uncertain',
  editors_notes:  'editors_notes',
  date_of_work2_approx:  'date_of_work2_approx',
  date_of_work2_std_day:  'date_of_work2_std_day',
  date_of_work2_inferred:  'date_of_work2_inferred',
  date_of_work2_std_month:  'date_of_work2_std_month',
  date_of_work2_uncertain:  'date_of_work2_uncertain',
  date_of_work2_std_year:  'date_of_work2_std_year',
  explicit:  'explicit',
  incipit:  'incipit',
  iwork_id:  'iwork_id',
  keywords:  'keywords',
  mentioned_as_marked:  'mentioned_as_marked',
  mentioned_inferred:  'mentioned_inferred',
  mentioned_uncertain:  'mentioned_uncertain',
  notes_on_addressees:  'notes_on_addressees',
  notes_on_authors:  'notes_on_authors',
  notes_on_date_of_work:  'notes_on_date_of_work',
  notes_on_destination:  'notes_on_destination',
  notes_on_letter:  'notes_on_letter',
  notes_on_origin:  'notes_on_origin',
  notes_on_people_mentioned:  'notes_on_people_mentioned',
  notes_on_place_mentioned:  'notes_on_place_mentioned',
  origin_id:  'origin_id',
  origin_as_marked:  'origin_as_marked',
  origin_inferred:  'origin_inferred',
  origin_uncertain:  'origin_uncertain',
  original_calendar:  'original_calendar',
  place_mentioned_as_marked:  'place_mentioned_as_marked',
  place_mentioned_inferred:  'place_mentioned_inferred',
  place_mentioned_uncertain:  'place_mentioned_uncertain',
  date_of_work_approx:  'date_of_work_approx',
  date_of_work_std_day:  'date_of_work_std_day',
  date_of_work_inferred:  'date_of_work_inferred',
  date_of_work_std_month:  'date_of_work_std_month',
  date_of_work_uncertain:  'date_of_work_uncertain',
  date_of_work_std_year:  'date_of_work_std_year',
  upload_id:  'upload_id',
  upload_name:  'upload_name',
  _id:  '_id'
};

module.exports = workMap;
